name: 'AutoUpdate'
 
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0/24 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: 'Run autoupdate.sh'
      run: bash ./autoupdate.sh
    - name: Commit files
      run: |
        git config --local user.email "github-actions@noreply.github.com"
        git config --local user.name "github-actions"
        if [ -n "$(git status -s)" ];then
        git add .
        git commit -m "Update `date "+%Y/%m/%d %H:%M"`"
        else
        echo "There is no merge commits."
        fi
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}


